Profile.create!(surname:'Kent', given_name:'Clark', group:'WDI')

Question.create!(topic:'Ruby methods')
Question.create!(topic:'HTML5')
Question.create!(topic:'CSS')
Question.create!(topic:'jQuery')
Question.create!(topic:'Ruby on Rails')
Question.create!(topic:'JS objects')
Question.create!(topic:'SQL CRUD')
Question.create!(topic:'Rails CRUD')
Question.create!(topic:'node.js')
Question.create!(topic:'ember.js')
Question.create!(topic:'BBQ')

Fist.create!(value:1, profile_id:1, question_id:1)
Fist.create!(value:2, profile_id:1, question_id:2)
Fist.create!(value:3, profile_id:1, question_id:3)
Fist.create!(value:4, profile_id:1, question_id:4)
Fist.create!(value:5, profile_id:1, question_id:5)
Fist.create!(value:1, profile_id:1, question_id:6)
Fist.create!(value:2, profile_id:1, question_id:7)
Fist.create!(value:3, profile_id:1, question_id:8)
Fist.create!(value:4, profile_id:1, question_id:9)
Fist.create!(value:5, profile_id:1, question_id:10)
Fist.create!(value:1, profile_id:1, question_id:11)
